name: run_py_test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_ACTION_TOKEN }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Py Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get and Stage POI Raw Data
      id: get-stage-poi-raw-data
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: python person_of_influence\scripts\get_poi_raw_data.py
    - name: Commit and Push Changes
      if: steps.get-stage-poi-raw-data.outcome == 'success'
      run: |
        git config --global user.name "dom-andolino"
        git config --global user.email "42012173+dom-andolino@users.noreply.github.com"
        git add *
        git commit -m "POI Workflow"
        git push origin main
